projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        local: http://localhost:4000
        dev: https://backend-dev.tm.mimacom.solutions
        prod: https://backend-prod.tm.mimacom.solutions
  database:
    schemaPath: src/gen/prisma.graphql
    extensions:
      endpoints:
        local: http://localhost:4466
        dev: https://prisma-dev.tm.mimacom.solutions
        prod: https://prisma-prod.tm.mimacom.solutions
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/gen/prisma.ts
