projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        local: http://localhost:4000
        dev: http://backend.dev.mimacom-tm.tk
        prod: http://backend.mimacom-tm.tk
  database:
    schemaPath: src/gen/prisma.graphql
    extensions:
      prisma: database/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/gen/prisma.ts
